### ISSUE TITLE
files from the tpl-fsLR not downloading

### ISSUE THREAD

**Issue by rubenSaro** [templateflow/templateflow#120]
Hi, 
when typing in terminal: datalad get -r tpl-fsLR

The following files are not downloading
![image](https://user-images.githubusercontent.com/40474901/153273535-27587d6a-bd69-4e07-a7a9-57c75a2b9902.png)

**Comment by oesteban** [comment]
Thanks for reporting. Please confirm that datalad get now works for you, and reopen if it doesn't

(please, do not forget to update your templateflow dataset with `datalad update -r --merge any .` )
