### ISSUE TITLE
tpl-MouseIn errors

### ISSUE THREAD

**Issue by eilidhmacnicol** [templateflow/templateflow#140]
(I tried to submit this to templateflow/tpl-MouseIn but that repository does not accept issues?)

Some files in tpl-MouseIn have been changed from float32 images to int16 causing issues:

- `tpl-MouseIn_res-1_T1map` should be an average T1 map of the brain in CCFv3 space, but the image type has been changed to an int16 from a float32 and consequently looks like a discrete segmentation of the cerebrum.
- `tpl-MouseIn_res-2_T1map` should be an average T1 map of the head which has also been changed from a float32 to int16 and also loses quantitative information, looking like another discrete segmentation of the head.
- `tpl-MouseIn_res-1_UNIT` should be an average T1w image of the brain, but it is empty.
- `tpl-MouseIn_res-2_UNIT` should be an average T1w image of the head, but it is empty.
- The values for `tpl-MouseIn_res-2_inv-?_MP2RAGE` have also been manipulated compared to the image values on osf. 

As the values in the T1 maps are quantitative (< 4 seconds) and the values of the UNIT1 images range between -0.5 and 0.5, this change of image type explains the problematic appearance of the images when downloaded. The tissue/brain masks and segmentations are fine but they haven't been transformed from float32 images. Does this change of image type happen at the upload stage or is it related to loading at the user end?

Additionally, the `res-1` images are skull stripped in OSF, so probably best to add `desc-brain` to those images too.

WDYT about most of the resources being described as `res-2`? I ask because only the T1 map and T1w image were transformed to the Allen Brain Atlas space (CCFv3), so most of the resources are not available in `res-1` (although CCFv3 space is higher resolution, so I understand that is why it is `res-1`).

**Comment by oesteban** [comment]
Concluded, in principle, with https://github.com/templateflow/tpl-MouseIn/commit/59491a0821b889ffba40bcb8f13545e65100b491

Please reopen if I'm wrong.

**Comment by oesteban** [comment]
Ugh, what's wrong?

**Comment by eilidhmacnicol** [comment]
Frustratingly, the new `res-2` (aka the CCFv3, skull-stripped images) are now floats, but the `res-1_UNIT1` and `res-1_T1map` are still downloading as int16...

**Comment by oesteban** [comment]
Okay, so the GIN copy was up-to-date, but the S3 mirror was locked in the broken version. I have updated them manually and will address the update pipeline hiccups at some point (probably, stopping the use of S3 completely).

This means, if your templateflow repository was handled by datalad, everything was fine, but if you were using the lightweight mode of operation (i.e., pulling directly URLs), then you got the old files.

Please delete your templateflow cache and try to pull again.

**Comment by oesteban** [comment]
Just double checked and it looks good now. Please remember to update your python client to the latest version available :)

**Comment by eilidhmacnicol** [comment]
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/54267723/167250353-c0055bc1-2e9d-4ddb-95f0-6d136fa2f620.png">
You have no idea how sorry I am to be the bearer of bad news, but now the image type isn't available for all the other images...

**Comment by eilidhmacnicol** [comment]
Okay, replicated on my other machine which has datalad. 

Same problem before setting `export TEMPLATEFLOW_USE_DATALAD=on`. Once setting to datalad and starting a new cache, the images are there and look good, so it seems the new problems are with the s3 mirror.

**Comment by oesteban** [comment]
I believe you have to update your TemplateFlow Client installation. You can either:
- Install / update an installation from sources (i.e., clone the git repo, pull the latest changes and pip install . or pip install -e .)
- Wait for ~20 min and upgrade the client to version 0.8.1 (which I have just cut).

**Comment by oesteban** [comment]
BTW, I'll leave the issue open until you confirm that was the cause of the problem :)

**Comment by eilidhmacnicol** [comment]
Confirmed with 0.8.1 - this is all good so I'm closing this 🎉
