### ISSUE TITLE
Add dHCP week-specific neonate templates

### ISSUE THREAD

**Issue by tsalo** [templateflow/templateflow#150]
There are a couple of projects that use, or will use, the dHCP neonate templates available [here](https://brain-development.org/brain-atlases/atlases-from-the-dhcp-project/), including Nibabies and XCP-D. It looks like the solution so far has been to upload the relevant files from these templates to the repo (e.g., https://github.com/nipreps/nibabies/pull/301), but it would be great if they could be added to TemplateFlow.

I don't know what the license is for those templates, and the files are not properly BIDS-formatted, so some processing will need to be done to add them. I'm willing to take a crack at adding the _surface_ templates following the [TemplateFlow submission guidelines](https://www.templateflow.org/contributing/submission/), once I know the license situation, but I also thought there might already be work being done on these templates, based on a discussion with @madisoth, and I don't want to duplicate any work.

**Comment by oesteban** [comment]
Any news on the licensing terms?

/cc @mgxd

**Comment by tsalo** [comment]
Sorry, I haven't contacted anyone yet. The website doesn't have any info on who to talk to about the atlases, so I'm following up with some folks on Slack to see if they know who to get in touch with on the dHCP team.

**Comment by arokem** [comment]
There are some rather responsive dhcp people who reply to questions on neurostars, so maybe that's a way to ask?

**Comment by tsalo** [comment]
That's a great idea @arokem! I just opened https://neurostars.org/t/license-for-dhcp-neonate-templates/26375.

**Comment by oesteban** [comment]
Okay, for the volumetric we are good since it is a [CC-BY](https://gin.g-node.org/BioMedIA/dhcp-volumetric-atlas-groupwise/src/d699540b1820d8224a07db3c1d727d0c747218dc/LICENSE.md). BTW, see https://gin.g-node.org/BioMedIA/dhcp-volumetric-atlas-groupwise/issues/1

The other two templates (surface) would require they update the distributed zip files with the license file.

**Comment by tsalo** [comment]
That's awesome to hear! I haven't gotten any responses for my NeuroStars post, so I think I'll email someone about the surface atlases.

**Comment by oesteban** [comment]
Additional good news is that thanks to @feilong, I've recently revised the submission pipeline and things are looking good to take new templates.

**Comment by oesteban** [comment]
I just updated the guidelines https://www.templateflow.org/contributing/submission/ in case it helps.

**Comment by tsalo** [comment]
I've hit some stumbling blocks with the new process. Would you prefer to work through it in this issue, in templateflow/python-manager#8, or in a new issue in `templateflow/python-manager`?

**Comment by tsalo** [comment]
@effigies @mgxd I've pushed the volumetric templates to G-Node GIN: https://gin.g-node.org/tsalo/tpl-dhcpVol.

**Comment by arokem** [comment]
Hey @tsalo : thank you so much for your work on this! Do you have any reference as to how those templates were generated?

**Comment by tsalo** [comment]
I believe the paper they cite in the GIN repo the templates come from is https://doi.org/10.1101/251512. The modifications I made to the images are in https://github.com/templateflow/tpl-dhcpVol/blob/2712f7615f296c1d2f30597f91c4236fdd8f4cd0/scripts/sanitize.py.
