### ISSUE TITLE
What's the meaning of "_res" and "_desc" in atlases templates and Nifiti Images

### ISSUE THREAD

**Issue by SaqibMamoon** [templateflow/templateflow#158]
Dear Authors,

Thanks a lot for such a great work. However, I am confused about that does it mean "_res" and "_desc" in the names of the templates and images provided like for "tpl-MNI152NLin2009cAsym**_res**-01_T1w.nii.gz" and "tpl-MNI152NLin2009cAsym_res-01**_desc**-brain_T1w.nii.gz". Could you please guide me through it. 

Thanks a lot. 
Regards,

**Comment by Remi-Gau** [comment]
Those are BIDS filename entities:
- https://bids-specification.readthedocs.io/en/latest/appendices/entities.html#res
- https://bids-specification.readthedocs.io/en/latest/appendices/entities.html#desc
