### ISSUE TITLE
Missing info from HOSPA atlas

### ISSUE THREAD

**Issue by wiheto** [templateflow/templateflow#16]
So I have noticed 3 issues regarding the HOSPA in the _dseg.tsv file. 

1. The _dseg file is missing from: MNI152NLin2009cAsym

2. The brainstem is missing in the _dseg file in MNI152NLin6Asym [link](https://github.com/templateflow/tpl-MNI152NLin6Asym/blob/6b13a677493cd380bd58cc48d514143217bc59ed/tpl-MNI152NLin6Asym_atlas-HOSPA_dseg.tsv). It currently reads:

```
6 	Left Pallidum 	54, 62, 35
8 	Left Hippocampus 	59, 54, 27
```

The brainstem is included in the nifti image. 

3. Finally the index of the _dseg.tsv starts at zero, but here (and in most atlases) the indexing starts at 1 in the image files. This could lead to greater confusion (for example the brainstem has a value 8 in the nifti file). While the xyz coordinates could be used to find the actual value, perhaps an additional column in the data for this information should be added? (Suggested column name: value)

I can PR a fix for all three of these things unless any of these are meant to be the case.

**Comment by wiheto** [comment]
Some additional problems while I was thinking about creating the .tsv for MNI152NLin2009cAsym:

- tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_atlas-HOSPA_probseg.nii.gz appears to be just 0s where it should be a 4d image (MNI152NLin6Asym is correct) 

- I thought about how to make the xyz cordinates for the new tsv file. But in the current .tsv file there are no negative coordinates! For example, the xyz is current 58,37,40 for the __left__ White matter. I'm not fully sure what these xyz correspond to (I would have assumed they were coordinates in the space they are within). But the max probability is at -42, -48, -2 (and if xyz were supposed to be indices of the image, that would be 25,40,36 and the probability at img[58,37,40,0] is 0.

**Comment by wiheto** [comment]
@oesteban So the updated tsv for HOSPA where there is brainstem can be found here: 

https://github.com/wiheto/tpl-MNI152NLin6Asym/blob/master/tpl-MNI152NLin6Asym_atlas-HOSPA_dseg.tsv

I believe I cannot update this directly due to the OSF account (but we can discuss this next week if you want).

**Comment by Shotgunosine** [comment]
I'd love to see the probseg file here fixed. Just got tripped up by this issue today.

**Comment by Shotgunosine** [comment]
It seems like there is also information missing from the HOCPAL look up table. There appear to be 93 distinct values in the HOCPAL atlas, but only 52 in the definitions file. Looking in the definitions file, there are a bunch of ranges of values missing. Is there some other definition file that should be combined with this?

Here's the code I used. If there is documentation somewhere about how to use these look up tables I'd be happy to refer to that.
```
HOCPAL_def_path = templateflow_home / 'tpl-MNI152NLin6Asym/tpl-MNI152NLin6Asym_atlas-HOCPAL_dseg.tsv'
HOCPAL_def = pd.read_csv(HOCPAL_def_path, sep='\t')
seg_path = templateflow_home / f'tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_atlas-HOCPAL_desc-th50_dseg.nii.gz'
seg_image = nli.image.load_img(seg_path.as_posix().replace('~', '/home/nielsond'))
val_counts = np.unique(seg_image.get_fdata(), return_counts=True)
val_counts = pd.DataFrame(np.array(val_counts).T, columns=['val', 'count'])
print(len(HOCPAL_def), len(val_counts))
```

**Comment by oesteban** [comment]
To recapitulate, the current templateflow version still has the following problems:
- MNI152NLin6Asym: Fix the three `_dseg.tsv` files with the improvements of @wiheto. @Shotgunosine just found that the same problem is present for HOCPAL. Let's follow up on that here templateflow/tpl-MNI152NLin6Asym#2
- MNI152NLin2009cAsym: Resample `tpl-MNI152NLin2009cAsym_res-02_atlas-HOSPA_probseg.nii.gz` again since currently it is all-zeros. Let's follow up on that one here templateflow/tpl-MNI152NLin2009cAsym#9

If you are okay, I will close this issue in favor of the other two. Of course, feel free to reopen if you feel this is not the right call.
