### ISSUE TITLE
PNC files not hosted on any public remote 

### ISSUE THREAD

**Issue by bpinsard** [templateflow/templateflow#176]
It looks like this commit migrated all the keys, invalidating all the old one , but it was not pushed to public remotes.

https://github.com/templateflow/tpl-PNC/commit/3d4fd9b425eb84f6925b081c19abb9378297a6b0

So effectively, the keys are not accessible.

```
git-annex list 
here
|gin-src
||origin
|||s3
||||web
|||||bittorrent
||||||
______ tpl-PNC_res-01_T1w.nii.gz
______ tpl-PNC_res-01_desc-BrainCerebellumExtraction_mask.nii.gz
______ tpl-PNC_res-01_desc-brain_T1w.nii.gz
______ tpl-PNC_res-01_desc-brain_mask.nii.gz
______ tpl-PNC_res-01_label-BS_probseg.nii.gz
______ tpl-PNC_res-01_label-CBM_probseg.nii.gz
______ tpl-PNC_res-01_label-CGM_probseg.nii.gz
______ tpl-PNC_res-01_label-CSF_probseg.nii.gz
______ tpl-PNC_res-01_label-SCGM_probseg.nii.gz
______ tpl-PNC_res-01_label-WM_probseg.nii.gz
______ tpl-PNC_res-01_label-brain_probseg.nii.gz
______ tpl-PNC_res-02_desc-brain_T1w.nii.gz
```

```
git-annex whereis tpl-PNC_res-01_T1w.nii.gz
whereis tpl-PNC_res-01_T1w.nii.gz (0 copies) failed
git-annex: whereis: 1 failed
``` 

@effigies do you still have the forks where the keys were migrated.

**Comment by effigies** [comment]
Do you have `datalad-osf` installed? I believe that's where they're hosted.

**Comment by effigies** [comment]
Okay, so the data are all accessible, but we need to teach s3 and gin that they have them. In the short term, you can fetch the data with:

```
git checkout 6fa5e21a90738a233f9f178a47b0bb78d4c45460
git annex get .
git annex migrate
git reset --hard master
```

**Comment by effigies** [comment]
A fresh clone should now work.

**Comment by bpinsard** [comment]
Thanks for the fix!
I likely didn't have OSF installed, but I would expect `git-annex whereis` to tell me it was there even if the special-remote was not enabled.
Also, `datalad-osf` is not a dependency of the templateflow python-client package (not even in optional ones), is it able to download from osf when not using the datalad backend?
