### ISSUE TITLE
needs a push for a submodule

### ISSUE THREAD

**Issue by yarikoptic** [templateflow/templateflow#4]
https://github.com/templateflow/tpl-MNI152Lin/tree/2d77e59af77897afef5ee385afddb1a9de57d12b
from the top dataset is a deadlink - I guess state wasn't pushed to github for that one

**Comment by oesteban** [comment]
Mmmm, weird. I've just pushed and it is still a deadlink.

**Comment by oesteban** [comment]
ooh wait, it is the submodule

**Comment by oesteban** [comment]
I think I fixed this with a datalad push :)
