### ISSUE TITLE
Intake process hitting snag at datalad create

### ISSUE THREAD

**Issue by oesteban** [templateflow/templateflow#50]
I'm getting this error:

```
[ERROR] 'SilentConsoleLog' object has no attribute 'question' [__init__.py:__getattribute__:101] (AttributeError) 
##[error]Process completed with exit code 1.
```

* Example run where this was triggered: https://github.com/templateflow/templateflow/runs/686235369?check_suite_focus=true

* Line of code where the error is generated:
https://github.com/templateflow/templateflow/blob/3c2f7ed396da7aa17ae1cb3ed1ba8026a0c94090/.github/workflows/build-submission.yaml#L82

**Comment by oesteban** [comment]
Setting the env variable `$GITHUB_TOKEN` with a proper PAT didn't work out (@yarikoptic). -  shouldn't that do it (https://github.com/github/hub)?

**Comment by oesteban** [comment]
I'm pretty stuck here, so sorry for the noise. Paging @mgxd and @effigies too for ideas.

- Setting the `GITHUB_TOKEN` environment variable does not seem to help (the prompt seems to still be issued). This should suffice for `hub` to access the GitHub API:

https://github.com/templateflow/templateflow/blob/b484568fac7a2c4c36d26c73abb05116e4bcdb3c/.github/workflows/build-submission.yaml#L65

- Tried to also set-up the `pushInsteadOf` configuration for git, which should use ssh protocol on git operations. If https were used, I don't think git honors the `GITHUB_TOKEN` env variable and the prompt for password would also be issued.

https://github.com/templateflow/templateflow/blob/b484568fac7a2c4c36d26c73abb05116e4bcdb3c/.github/workflows/build-submission.yaml#L36

- I've also checked how to pass the PAT in the command line:
  ```
  $ datalad create-sibling-github --help
  ...
    --github-login NAME   Github user name or access token.
  ...
  ```
  That (https://github.com/templateflow/templateflow/blob/984f2eade443e836be4a13a4d7b1a738f0cc169c/.github/workflows/build-submission.yaml#L89) [didn't pacify the prompt either](https://github.com/templateflow/templateflow/runs/687322150?check_suite_focus=true).

- I think setting the oauth token in the hub config file is the only experiment left here (https://github.com/github/hub/issues/1488#issuecomment-310070939). I'm not thrilled by this - although GH actions should redact secrets from all output I would rather not put it in a file. It'd be great to confirm that none of the previous alternatives is going to work.

**Comment by yarikoptic** [comment]
I don't think we consume GitHub_token env var atm. Just have `git config --global --set hub.token $SECRET` command (typing on the phone ATM, can check exact invocation trio do later on) to store it in config. This is completely orthogonal from push / ssh. We don't use token to push, only to create repo on GitHub

**Comment by oesteban** [comment]
That didn't seem to help (https://github.com/templateflow/templateflow/runs/688137462?check_suite_focus=true#step:9:5)

offtopic: is the `--set` necessary?

**Comment by yarikoptic** [comment]
> offtopic: is the `--set` necessary?

apparently not... I mixed up with `git annex config` which has it, heh

**Comment by oesteban** [comment]
And regarding the actual issue... any ideas anyone?

**Comment by yarikoptic** [comment]
btw -- what is that ssh key exactly?  is it a "deploy key"? then those are assigned per repository IIRC, but here you are creating a new repository on github so it would have None.

**Comment by oesteban** [comment]
> what is that ssh key exactly?

Which one? If you refer to this (now commented out) piece of code:

https://github.com/templateflow/templateflow/blob/tpl-intake/.github/workflows/build-submission.yaml#L55-L58

This was thought out to install the private ssh key of a machine user (with r/w permissions to the templateflow/ repos) in the ssh agent. Meaning, this was attempted to make git use the ssh protocol easily. I have tried this pattern elsewhere and it worked.

A difference with other instances where I have installed the ssh key and then pushed commits to some repo is that datalad uses https by default, and that's why I asked about how to go around that:

https://github.com/templateflow/templateflow/blob/tpl-intake/.github/workflows/build-submission.yaml#L59-L63

I cannot tell whether this did the trick, because we are being held up one step earlier when datalad creates the new git sibling for this particular template we are updating.

Then, I had to pivot to the solution with the authorization token:

https://github.com/templateflow/templateflow/blob/tpl-intake/.github/workflows/build-submission.yaml#L72-L76

And that did not seem to work either. In particular, I'm setting:

```
git config --global hub.token ${{ secrets.NIPREPS_BOT_PAT }}
```
as per Hub's documentation, and
```
git config --global hub.oauthtoken ${{ secrets.NIPREPS_BOT_PAT }}
```
as per DataLad's documentation.

What I'm missing?

**Comment by oesteban** [comment]
I'll add, I think I have also (unsuccessfully) tried setting `GITHUB_PASSWORD` with the token, as that env variable is also observed by Hub.

**Comment by oesteban** [comment]
@yarikoptic with the latest rc2:

```
[ERROR] A non-interactive silent UI was asked for a response to a question: password. Title: You need to authenticate with '***@github' credentials. https://github.com/login provides information on how to gain access. Additional arguments are not shown because 'hidden' is set. [dialog.py:question:137] (RuntimeError) 
```

I don't think we gained much, other than confirming that the problem is on authentication

**Comment by oesteban** [comment]
I'm quite stuck here @yarikoptic - any new ideas?

maybe @mih could also be paged here?

**Comment by yarikoptic** [comment]
oh man, sorry so much for forgetting about this one.  So password is asked for , and it is for a "***" login?
```
password. Title: You need to authenticate with '***@github'
```
how that one comes about yet to be figured out

**Comment by oesteban** [comment]
This is hub asking for a password right?

**Comment by yarikoptic** [comment]
I guess so... but why login is `***`? when I try locally:

```
$> ( GITHUB_USER=nipreps-bot; echo '' | HOME=/tmp datalad create-sibling-github --github-organization templateflow --github-login $GITHUB_USER --access-protocol ssh TEST | cat)
It is highly recommended to configure Git before using DataLad. Set both 'user.name' and 'user.email' configuration variables.
It is highly recommended to configure Git before using DataLad. Set both 'user.name' and 'user.email' configuration variables.
[ERROR] A non-interactive silent UI was asked for a response to a question: password. Title: You need to authenticate with 'nipreps-bot@github' credentials. https://github.com/login provides information on how to gain access. Additional arguments are not shown because 'hidden' is set. [dialog.py:question:139] (RuntimeError) 
```
I do get `nipreps-bot@github` reported

**Comment by yarikoptic** [comment]
and did you try to run commands locally mimicing what you do in https://github.com/templateflow/templateflow/blob/tpl-intake/.github/workflows/build-submission.yaml#L75 ?  I would have done that with some fake $HOME (like I did above) and set that hub.oauthtoken.. I also think you better not provide ` --github-login ${NIPREPS_PAT} `

<details>
<summary>I just did evil</summary> 

```shell
$> ( GITHUB_USER=nipreps-bot; echo '' | HOME=/tmp datalad create-sibling-github --github-organization templateflow  --access-protocol ssh TEST | cat)        
It is highly recommended to configure Git before using DataLad. Set both 'user.name' and 'user.email' configuration variables.
It is highly recommended to configure Git before using DataLad. Set both 'user.name' and 'user.email' configuration variables.
[INFO] Successfully obtained information about organization templateflow using UserPassword(name='github', url='https://github.com/login') credential 
.: github(-) [git@github.com:templateflow/TEST.git (git)]
'git@github.com:templateflow/TEST.git' configured as sibling 'github' for Dataset(/home/yoh/proj/datalad/datalad)
( GITHUB_USER=nipreps-bot ; echo '' | HOME=/tmp datalad create-sibling-github)  3.73s user 1.67s system 69% cpu 7.744 total

```

I guess it took my credentials and/or token... dunno - but it worked... will remove that TEST now
</details>

**Comment by oesteban** [comment]
> I also think you better not provide `--github-login ${NIPREPS_PAT}`

Yeah, I've been thinking about that. Since the token is written in the config, this should not be necessary right?

**Comment by yarikoptic** [comment]
it might even interfere, e.g. if token is not associated with that login... it should have worked if token is for that login though.

**Comment by oesteban** [comment]
> it should have worked if token is for that login though.

It is for that login. But removing the `--github-login` seems to have worked out! Thanks much!

I'm closing this one. Let me know if you want to dig into this in the context of datalad and how I can help.
