### ISSUE TITLE
datalad: demo script for full loop publishing (exported tree) to S3 as a dependency

### ISSUE THREAD

**Issue by yarikoptic** [templateflow/templateflow#54]
also add `dead` #52

**Comment by oesteban** [comment]
I believe I might just deprecated this issue with two changes:

1. The loop will be removed - it doesn't seem to make a lot of sense to export all datasets if only one has changed. To achieve this, I have moved the export call to the *update dataset* action - https://github.com/templateflow/actions-template/blob/9f99e4fa8d23a6817d9192e12ee64814fc447008/entrypoint.sh#L35-L40 triggered with any change to the github repo of the particular template.
2. That workflow has been wrapped up as a GH action - if that counts as "demo script" that can be understood as a dependency.

Please reopen if the above is not satisfying.
