### ISSUE TITLE
Add template: MNI152NLin6Sym

### ISSUE THREAD

**Issue by oesteban** [templateflow/templateflow#6]
[comes from https://github.com/poldracklab/smriprep/issues/11]

http://nist.mni.mcgill.ca/?p=858

As per the original discussion, ``MNI152NLin6ASym`` was proposed. However, I can't find such template on the MNI website. @feilong, could you confirm that you are interested in the **symmetric** template (i.e., ``MNI152NLin6Sym``)?

**Comment by feilong** [comment]
Hi @oesteban , my purpose then was to make it possible to apply atlases available in FSL to fmriprep outputs. I cannot recall the details, but from the records it seems it should be the **asymmetric** version.

**Comment by oesteban** [comment]
Could you provide us with the link?

**Comment by feilong** [comment]
I don't know where the source is, but it's available as part of FSL: http://neuro.debian.net/pkgs/fsl-mni152-templates.html

**Comment by oesteban** [comment]
Okay, as per their documentation (https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/Atlases) FSL's atlas *corresponds to the "152 nonlinear 6th generation" atlas*. So I guess that the only existing version is the Symmetric one.

**Comment by feilong** [comment]
Based on the original discussion (https://github.com/poldracklab/fmriprep/issues/337) and the reference (http://www.lead-dbs.org/?p=1241) the **asymmetric** version was used, but that version isn't available from the official website...

**Comment by jnvandermeer** [comment]
I tried to look for the asymmetric version of MNI152 -6- Nlim:
http://packages.bic.mni.mcgill.ca/mni-models/icbm152/mni_icbm152_nl_VI_minc2.zip -- BUT - these consist of only symmetric images.

We have the same issue now that we wish to have processed bold images using the MNI152Nlim6Asym space (to be consistent with other work), and are looking to apply a deformation field to the images as a final processing step. It appears that the difference between version 6 and version 2009c of these templates is a position shift and a stretch in A-P direction.

Does anyone has a good link for the MNI152Nlim6Asym in nifti format? Or is it as easy as taking the T1 image from the fsl package (in /fsl/5.0/data/standard/MNI152_T1_1mm_brain.nii.gz)?

Thanks for your time
Johan

**Comment by vfonov** [comment]
in 2006 we did not create asymmetric version.

**Comment by oesteban** [comment]
I see, I'll ping the FSL list to check the provenance of the asymmetric version. Thanks very much Vladimir.

**Comment by vfonov** [comment]
Maybe @andrewjanke was involved in that

**Comment by andrewjanke** [comment]
Yes, I made the FSL model. It was made using a nigh on identical method to Vlad's. We were in the same room at the time under Louis and were pretty much writing code to do this at the same time. Perhaps mine predated his slightly. My Perl version was volgenmodel (https://github.com/andrewjanke/volgenmodel) vlads was in Ruby IIRC. make_a_model?  

There is also a NiPypy version of volgenmodel: https://github.com/carlohamalainen/volgenmodel-nipype

I would still have the original files somewhere, a nonlinear match between them was made at some point in time. Both to the nl6 and to the previous FSL models.

vlad you may be able to find these in ~rotor/data on the MNI systems.

**Comment by vfonov** [comment]
yes, my code is in https://github.com/vfonov/build_average_model 
And the python version is a module model in the pipeline code: https://github.com/vfonov/nist_mni_pipelines

**Comment by oesteban** [comment]
@andrewjanke would you be willing to provide the original file set for us to add it as a template to this repository? As you can see, we are trying to provide a regular interface to all (possible) templates (and associated atlases and metadata).

BTW @vfonov, we would love to hear any feedback from your expert perspective (same for Andrew). Please let us know any thoughts if there are some.

**Comment by oesteban** [comment]
Hi @andrewjanke, what is/are the most relevant references that should be present when using the asymmetric template you created (i.e. when using FSL's template)?

**Comment by oesteban** [comment]
I've just finished adding both templates and indexing them within the superdataset.

**Comment by andrewjanke** [comment]
Likely this:

10.1016/j.neuroimage.2012.01.024

A

**Comment by Shotgunosine** [comment]
Hi @oesteban,

Sorry for resurrecting this issue, but it seemed like the most appropriate place to raise this issue. The MNI152NLin6Asym in template flow has left right orientation flipped relative to the FSL template.
```
(/gpfs/gsfs10/users/MLDSST/nielsond/target_test/env) [nielsond@biowulf func]$ 3dinfo ~/.cache/templateflow/tpl-MNI152NLin6Asym/tpl-MNI152NLin6Asym_res-02_T1w.nii.gz
++ 3dinfo: AFNI version=AFNI_23.0.04 (Feb 13 2023) [64-bit]

Dataset File:    /home/nielsond/.cache/templateflow/tpl-MNI152NLin6Asym/tpl-MNI152NLin6Asym_res-02_T1w.nii.gz
Identifier Code: NII_OmFAp4iniMhJbJVwxRX34A  Creation Date: Tue Feb 14 09:38:21 2023
Template Space:  MNI
Dataset Type:    Anat Bucket (-abuc)
Byte Order:      LSB_FIRST {assumed} [this CPU native = LSB_FIRST]
Storage Mode:    NIFTI
Storage Space:   1,805,258 (1.8 million) bytes
Geometry String: "MATRIX(-2,0,0,90,0,-2,0,126,0,0,2,-72):91,109,91"
Data Axes Tilt:  Plumb
Data Axes Orientation:
  first  (x) = Left-to-Right
  second (y) = Posterior-to-Anterior
  third  (z) = Inferior-to-Superior   [-orient LPI]
R-to-L extent:   -90.000 [R] -to-    90.000 [L] -step-     2.000 mm [ 91 voxels]
A-to-P extent:   -90.000 [A] -to-   126.000 [P] -step-     2.000 mm [109 voxels]
I-to-S extent:   -72.000 [I] -to-   108.000 [S] -step-     2.000 mm [ 91 voxels]
Number of values stored at each pixel = 1
  -- At sub-brick #0 '?' datum type is short

(/gpfs/gsfs10/users/MLDSST/nielsond/target_test/env) [nielsond@biowulf func]$ 3dinfo $FSLDIR/data/standard/MNI152_T1_2mm.nii.gz
++ 3dinfo: AFNI version=AFNI_23.0.04 (Feb 13 2023) [64-bit]

Dataset File:    /usr/local/apps/fsl/6.0.4/data/standard/MNI152_T1_2mm.nii.gz
Identifier Code: NII_6bs6XwUMRezWpHSdeQmtBQ  Creation Date: Tue Feb 14 09:38:25 2023
Template Space:  MNI
Dataset Type:    Anat Bucket (-abuc)
Byte Order:      LSB_FIRST {assumed} [this CPU native = LSB_FIRST]
Storage Mode:    NIFTI
Storage Space:   1,805,258 (1.8 million) bytes
Geometry String: "MATRIX(2,0,0,-90,0,-2,0,126,0,0,2,-72):91,109,91"
Data Axes Tilt:  Plumb
Data Axes Orientation:
  first  (x) = Right-to-Left
  second (y) = Posterior-to-Anterior
  third  (z) = Inferior-to-Superior   [-orient RPI]
R-to-L extent:   -90.000 [R] -to-    90.000 [L] -step-     2.000 mm [ 91 voxels]
A-to-P extent:   -90.000 [A] -to-   126.000 [P] -step-     2.000 mm [109 voxels]
I-to-S extent:   -72.000 [I] -to-   108.000 [S] -step-     2.000 mm [ 91 voxels]
Number of values stored at each pixel = 1
  -- At sub-brick #0 '?' datum type is short
```

**Comment by oesteban** [comment]
Correct, templates are reoriented to RAS+ before upload. Data should have
been modified accordingly.
