### ISSUE TITLE
template to fsaverage5

### ISSUE THREAD

**Issue by tanjia123456** [templateflow/templateflow#81]
hi, I have a question to ask you. I want let rh.white template to fsaverage5.
I know can use mri_surf2surf, but I don't know how to set the parameters（srcsurfval、 src_type 、trg_surf）
mri_surf2surf --srcsubject bert --srcsurfval thickness --src_type curv --trg_type curv --trgsubject fsaverage5 --trgsurfval white --hemi rh

so, How to set these parameters for rh.white?

**Comment by oesteban** [comment]
Sorry @tanjia123456 for coming back to you this late. This is a question for the freesurfer mailing list, templateflow does not have anything to do here. Thanks for posting.
