### ISSUE TITLE
Add template: MNIPediatricAsym

### ISSUE THREAD

**Issue by oesteban** [templateflow/templateflow#9]
(from poldracklab/smriprep#24)

http://nist.mni.mcgill.ca/?p=974

**Comment by JoffJones** [comment]
Hi there,
I was just wondering if there are any updates for the implementation of a pediatric template in fmriprep? 
This would be fantastically useful for my current project!
Many thanks,
Joff

**Comment by oesteban** [comment]
Hi @JoffJones, we just added this template. Will release a new version of the client and fmriprep including it ASAP.

**Comment by JoffJones** [comment]
Hi @oesteban, that's great news. Thanks so much!

Do you know if the new child template will work with ica-aroma? I tried using the PNC template but got the error that ica-aroma is only supported in the standard MNI template.

Thanks,
Joff

**Comment by oesteban** [comment]
ICA AROMA was trained on components extracted from images aligned AND resampled into that space and grid.

In other words, even if you regrid to match the FSL MNI template, the components and annotations are in a different space, so the results won't be great.

**Comment by JoffJones** [comment]
Thank you that's clear. In that case, I will do a two stage normalization firstly to the child template in fmriprep and then to the adult MNI template outside of fmriprep.
