### ISSUE TITLE
TemplateFlow Upload Issue

### ISSUE THREAD

**Issue by tstoica** [templateflow/templateflow#94]
When running this command - tfmgr add tpl-f2gzd/ f2gzd

I get this error - 
Traceback (most recent call last):
  File "/Users/tstoica/Library/Python/3.9/bin/tfmgr", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click-8.0.1-py3.9.egg/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click-8.0.1-py3.9.egg/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click-8.0.1-py3.9.egg/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click-8.0.1-py3.9.egg/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click-8.0.1-py3.9.egg/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/tstoica/Library/Python/3.9/lib/python/site-packages/tfmanager/cli.py", line 92, in add
    metadata = json.loads((path / "template_description.json").read_text())
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 34 column 5 (char 712)

Help?

**Comment by oesteban** [comment]
Looks like one of your JSON files is incorrectly formatted (missing closing parens or brackets, missing semicolon, unexpected semicolon, etc.)

**Comment by tstoica** [comment]
Thanks ! Can you take a look and see what may be wrong? I had to make it manually, so I'm not surprised there are mistakes. 

{
	"Authors": [
	"John C. Mazziota",
	"Arthur W. Toga",
	"Alan Evans",
	"Peter Fox",
	"Jack Lancaster" 
	],
	"Curators": [
	"Teodora Stoica, PhD"
	],
	"Identifier": "ICBM_452_T1_Warp5_Atlas",
	"License": "UCLA-derived. See LICENSE file",
	"Name": "Average of T1-weighted MRIs of normal young adult brains, N=100, Ages 20-40",
	"RRID": "SRC_004525",
	"ReferencesandLinks": [
	"https://www.sciencedirect.com/science/article/pii/S1053811985710129?via%3Dihub",
	"http://www.bmap.ucla.edu/portfolio/atlases/ICBM_452_T1_Atlas/"
	],
	"TemplateFlowVersion": "1.0.0",
	"cohort": {
		"1": {
			"age": [
				20,
				40
			],
			"name": "whole age range",
			"units": "yr"}
	},
	"res": {
		"1": {
			"origin": [
				-90
				-126
				-72
			],
			"shape": [
				197,
				233,
				189
			],
			"zooms": [
				1,
				1,
				1
			]
		}
	"SeriesNumber": 512362125,
	}

**Comment by oesteban** [comment]
There were several issues:

```JSON
{
    "Authors":
    [
        "John C. Mazziota",
        "Arthur W. Toga",
        "Alan Evans",
        "Peter Fox",
        "Jack Lancaster"
    ],
    "Curators":
    [
        "Teodora Stoica, PhD"
    ],
    "Identifier": "ICBM_452_T1_Warp5_Atlas",
    "License": "UCLA-derived. See LICENSE file",
    "Name": "Average of T1-weighted MRIs of normal young adult brains, N=100, Ages 20-40",
    "RRID": "SRC_004525",
    "ReferencesandLinks":
    [
        "https://www.sciencedirect.com/science/article/pii/S1053811985710129?via%3Dihub",
        "http://www.bmap.ucla.edu/portfolio/atlases/ICBM_452_T1_Atlas/"
    ],
    "TemplateFlowVersion": "1.0.0",
    "cohort":
    {
        "1":
        {
            "age":
            [
                20,
                40
            ],
            "name": "whole age range",
            "units": "yr"
        }
    },
    "res":
    {
        "1":
        {
            "origin":
            [
                -90,
                -126,
                -72
            ],
            "shape":
            [
                197,
                233,
                189
            ],
            "zooms":
            [
                1,
                1,
                1
            ]
        }
    },
    "SeriesNumber": 512362125
}
```
I would recommend you install a plugin to validate JSON on the IDE (integrated development environment) you are using. For example, I use Sublime Text with the "Pretty JSON" plugin. The plugin allows me to both validate, and then format JSON files.

**Comment by tstoica** [comment]
This was helpful thank you!
